In [2]:
!pip install tensorflow

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 601.3/601.3 MB 2.6 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.5/57.5 kB 9.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.5/24.5 MB 41.0 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.5/65.5 kB 11.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.1/5.1 MB 59.9 MB/s eta 0:00:0000:01:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 57.3 MB/s eta 0:00:0000:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 67.7 MB/s eta 0:00:0000:01:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 47.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 80.3/80.3 kB 11.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.7/5.7 MB 67.0 MB/s eta 0:00:0000:01:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.3/5.3 MB 69.1 MB/s eta 0:00:00:00:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.7/133

### 1. What are the different data structures used in TensorFlow? Give some examples.


#### Ans: 
#### TensorFlow uses several data structures to represent data:

1. Tensors: The core data structure in TensorFlow, analogous to arrays in NumPy. Tensors can be scalars, vectors, matrices, or higher-dimensional arrays.
Example: tf.constant([1, 2, 3]) creates a 1D tensor.

2. Variables: Mutable data structures used to store model parameters.
Example: tf.Variable([1, 2, 3]) creates a variable tensor.


3. Datasets: Used for input pipelines, representing a sequence of elements.
Example: tf.data.Dataset.from_tensor_slices([1, 2, 3]) creates a dataset from a tensor.

### 2. How does the TensorFlow constant differ from a TensorFlow variable? Explain with an example.

### Ans :
TensorFlow Constant: Immutable once defined. It's useful for values that don't change during execution.

In [1]:
## Example:
import tensorflow as tf
const = tf.constant([1, 2, 3])
print(const)

2024-08-04 17:17:24.787225: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-08-04 17:17:24.793116: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-08-04 17:17:24.814051: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-08-04 17:17:24.845482: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-08-04 17:17:24.854833: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-08-04 17:17:24.878159: I tensorflow/core/platform/cpu_feature_gu

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [2]:
# TensorFlow Variable: Mutable and can be updated during execution, useful for model parameters that need to be learned.

# Example:

var = tf.Variable([1, 2, 3])
var.assign([4, 5, 6])
print(var)

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([4, 5, 6], dtype=int32)>


### 3. Describe the process of matrix addition, multiplication, and element-wise operations in TensorFlow.
#### Ans: 
1. Matrix Addition: Adding corresponding elements of two matrices.
Example: tf.add(A, B)

2. Matrix Multiplication: Performing the dot product of two matrices.
Example: tf.matmul(A, B)

3. Element-wise Operations: Applying operations element by element.
Example: tf.multiply(A, B) for element-wise multiplication.

## Part 2: Practical Implementation
### Task 1: Creating and Manipulating Matrices

#### 1. Create a normal matrix A with dimensions 2x2, using TensorFlow's random_normal function. Display the values of matrix A.1. Create a normal matrix A with dimensions 2x2, using TensorFlow's random_normal function. Display the values of matrix A.

In [3]:
import tensorflow as tf

A = tf.random.normal([2, 2])
print("Matrix A:\n", A)


Matrix A:
 tf.Tensor(
[[-0.19418694 -0.67237973]
 [ 0.04147089 -0.3035688 ]], shape=(2, 2), dtype=float32)


#### 2. Create a Gaussian matrix B with dimensions 2x2, using TensorFlow's truncated_normal function. Display the values of matrix B.

In [4]:
B = tf.random.truncated_normal([2, 2])
print("Matrix B:\n", B)


Matrix B:
 tf.Tensor(
[[ 0.06368832  0.00738523]
 [ 0.5687476  -1.5849042 ]], shape=(2, 2), dtype=float32)


#### 3. Create a matrix C with dimensions 2x2, where the values are drawn from a normal distribution with a mean of 2 and a standard deviation of 0.5, using TensorFlow's random.normal function. Display the values of matrix C.

In [5]:
C = tf.random.normal([2, 2], mean=2, stddev=0.5)
print("Matrix C:\n", C)


Matrix C:
 tf.Tensor(
[[1.4163885 2.0113058]
 [2.2940893 1.5956438]], shape=(2, 2), dtype=float32)


#### 4. Perform matrix addition between matrix A and matrix B, and store the result in matrix D.

In [6]:
D = tf.add(A, B)
print("Matrix D (A + B):\n", D)


Matrix D (A + B):
 tf.Tensor(
[[-0.13049862 -0.6649945 ]
 [ 0.61021847 -1.888473  ]], shape=(2, 2), dtype=float32)


#### 5. Perform matrix multiplication between matrix C and matrix D, and store the result in matrix E.

In [7]:
E = tf.matmul(C, D)
print("Matrix E (C * D):\n", E)


Matrix E (C * D):
 tf.Tensor(
[[ 1.0424992 -4.740187 ]
 [ 0.6743158 -4.538887 ]], shape=(2, 2), dtype=float32)


### Task 2: Performing Additional Matrix Operations

#### 1. Create a matrix F with dimensions 2x2, initialized with random values using TensorFlow's random_uniform function.

In [8]:
F = tf.random.uniform([2, 2])
print("Matrix F:\n", F)


Matrix F:
 tf.Tensor(
[[0.8317392  0.6056981 ]
 [0.73288524 0.19762564]], shape=(2, 2), dtype=float32)


#### 2. Calculate the transpose of matrix F and store the result in matrix G.

In [9]:
G = tf.transpose(F)
print("Matrix G (transpose of F):\n", G)


Matrix G (transpose of F):
 tf.Tensor(
[[0.8317392  0.73288524]
 [0.6056981  0.19762564]], shape=(2, 2), dtype=float32)


#### 3. Calculate the element-wise exponential of matrix F and store the result in matrix H.

In [10]:
H = tf.exp(F)
print("Matrix H (element-wise exponential of F):\n", H)


Matrix H (element-wise exponential of F):
 tf.Tensor(
[[2.2973108 1.8325311]
 [2.0810764 1.2185061]], shape=(2, 2), dtype=float32)


#### 4. Create a matrix I by concatenating matrix F and matrix G horizontally.

In [11]:
I = tf.concat([F, G], axis=1)
print("Matrix I (F concatenated with G horizontally):\n", I)


Matrix I (F concatenated with G horizontally):
 tf.Tensor(
[[0.8317392  0.6056981  0.8317392  0.73288524]
 [0.73288524 0.19762564 0.6056981  0.19762564]], shape=(2, 4), dtype=float32)


#### 5. Create a matrix J by concatenating matrix F and matrix H vertically.

In [12]:
J = tf.concat([F, H], axis=0)
print("Matrix J (F concatenated with H vertically):\n", J)


Matrix J (F concatenated with H vertically):
 tf.Tensor(
[[0.8317392  0.6056981 ]
 [0.73288524 0.19762564]
 [2.2973108  1.8325311 ]
 [2.0810764  1.2185061 ]], shape=(4, 2), dtype=float32)
